const { Plugin, Notice } = require("obsidian");
module.exports = class PointixSheetCopy extends Plugin {
 async onload(){
  this._cachedApi=null;this._lastFilePath=null;this._lastFileMtime=null;this._sheetCache=null;this._lastApiCell=null;this._boundApi=null;this._apiEventDisposers=[];
  this._lastTap=null;this._blockedPointerId=null;this._lastCopyAt=0;this._dt=430;this._dd=34;
  this._cr=this._onCopyRequest.bind(this);this._pd=this._onPointerDown.bind(this);this._pu=this._onPointerUp.bind(this);this._cg=this._guard.bind(this);
  document.addEventListener("pointix-sheet-copy-request",this._cr,true);document.addEventListener("pointerdown",this._pd,true);document.addEventListener("pointerup",this._pu,true);document.addEventListener("click",this._cg,true);document.addEventListener("dblclick",this._cg,true);
  this.registerEvent(this.app.vault.on("modify",f=>{if(f?.path===this._lastFilePath){this._lastFileMtime=null;this._sheetCache=null}}));
  this.registerInterval(window.setInterval(()=>this._ensureApiEvents(),1800));window.setTimeout(()=>this._ensureApiEvents(),650);
  new Notice("Pointix Sheet Copy activo");
 }
 onunload(){document.removeEventListener("pointix-sheet-copy-request",this._cr,true);document.removeEventListener("pointerdown",this._pd,true);document.removeEventListener("pointerup",this._pu,true);document.removeEventListener("click",this._cg,true);document.removeEventListener("dblclick",this._cg,true);this._clearApiEvents()}
 _nav(){try{return !!this.app?.plugins?.enabledPlugins?.has?.("pointix-sheet-navigation")}catch(_){return false}}
 _touch(e){const p=String(e?.pointerType||"").toLowerCase();return p==="touch"||p==="pen"}
 _sheet(e){try{return(typeof e.composedPath==="function"?e.composedPath():[]).some(n=>String(n?.className||"").toLowerCase().includes("univer")||String(n?.id||"").toLowerCase().includes("univer")||String(n?.tagName||"").toUpperCase()==="CANVAS")}catch(_){return false}}
 _eat(e){try{e.preventDefault()}catch(_){}try{e.stopPropagation()}catch(_){}try{e.stopImmediatePropagation?.()}catch(_){}}
 async _onCopyRequest(){this._lastCopyAt=Date.now();await new Promise(r=>window.setTimeout(r,18));await this._copyBest()}
 _onPointerDown(e){
  if(this._nav()||!this._touch(e)||!this._sheet(e))return;
  const now=Date.now(),x=Number(e.clientX||0),y=Number(e.clientY||0),p=this._lastTap;
  if(p&&now-p.time>0&&now-p.time<=this._dt&&Math.hypot(x-p.x,y-p.y)<=this._dd){this._blockedPointerId=e.pointerId;this._lastTap=null;this._lastCopyAt=now;this._eat(e);void this._copyBest()}
 }
 _onPointerUp(e){
  if(this._touch(e)){if(this._nav())return;if(this._blockedPointerId!==null&&e.pointerId===this._blockedPointerId){this._eat(e);this._blockedPointerId=null;return}if(this._sheet(e))this._lastTap={time:Date.now(),x:Number(e.clientX||0),y:Number(e.clientY||0)};return}
  if((e.ctrlKey||e.metaKey)&&this._sheet(e))window.setTimeout(()=>void this._copyBest(),20);
 }
 _guard(e){if(!this._lastCopyAt||Date.now()-this._lastCopyAt>900||!this._sheet(e))return;this._eat(e)}
 async _copyBest(){this._ensureApiEvents();const p=this._lastApiCell||await this._getSelectedCellPosition(true);if(!p){new Notice("Pointix: no pude detectar la celda");return false}return this._copyFromPosition(p.row,p.col,p.sheetId,p.sheetName)}
 _ensureApiEvents(){const api=this._findUniverApi();if(!api||api===this._boundApi)return;this._clearApiEvents();this._boundApi=api;this._cachedApi=api;for(const n of["CellPointerDown","CellPointerUp","CellClicked"]){try{const k=api?.Event?.[n];if(!k)continue;const d=api.addEvent(k,p=>this._remember(p));if(typeof d==="function")this._apiEventDisposers.push(d);else if(d?.dispose)this._apiEventDisposers.push(()=>d.dispose())}catch(_){}}}
 _clearApiEvents(){for(const d of this._apiEventDisposers||[])try{d()}catch(_){}this._apiEventDisposers=[];this._boundApi=null}
 _remember(p){const row=Number(p?.row),col=Number(p?.column??p?.col);if(!Number.isInteger(row)||!Number.isInteger(col)||row<0||col<0)return;const ws=p?.worksheet;let sheetId="",sheetName="";try{sheetId=String(ws?.getSheetId?.()??ws?.getId?.()??"")}catch(_){}try{sheetName=String(ws?.getName?.()??ws?.getSheetName?.()??"")}catch(_){}this._lastApiCell={row,col,sheetId,sheetName,time:Date.now()}}
 async _load(){const f=this.app.workspace.getActiveFile();if(!f||f.extension!=="md")return null;const mt=Number(f.stat?.mtime||0);if(this._lastFilePath===f.path&&this._lastFileMtime===mt&&this._sheetCache)return this._sheetCache;const raw=await this.app.vault.read(f),m=raw.match(/```sheet\s*([\s\S]*?)```/);if(!m)return null;let book;try{book=JSON.parse(m[1])}catch(_){return null}const textOf=c=>{if(!c)return"";if(c.v!==undefined&&c.v!==null)return String(c.v).trim();const ds=c?.p?.body?.dataStream;if(ds!==undefined&&ds!==null)return String(ds).replace(/\r\n/g,"\n").replace(/\r/g,"\n").replace(/\n+$/g,"").trim();const rs=c?.p?.body?.customRanges;if(Array.isArray(rs))for(const r of rs)if(r?.properties?.url)return String(r.properties.url).trim();return""};const sheets=new Map();for(const[id,sh]of Object.entries(book.sheets||{}))sheets.set(id,{id,name:sh.name||"",cellData:sh.cellData||{},textOf});this._lastFilePath=f.path;this._lastFileMtime=mt;return this._sheetCache={book,sheets}}
 _resolve(d,id,name){if(!d)return null;let i=id&&d.sheets.has(String(id))?d.sheets.get(String(id)):null;if(!i&&name)for(const x of d.sheets.values())if(x.name===name){i=x;break}if(!i){const first=d.book.sheetOrder?.[0];i=d.sheets.get(first)||[...d.sheets.values()][0]}return i||null}
 async _copyFromPosition(row,col,id,name){const d=await this._load(),i=this._resolve(d,id,name);if(!i)return false;const c=i.cellData?.[String(row)]?.[String(col)]??i.cellData?.[row]?.[col],v=i.textOf(c);if(!v){new Notice("Pointix: celda vacía o no legible");return false}return this._clip(v)}
 async _clip(v){try{await navigator.clipboard.writeText(String(v));new Notice("Celda copiada");return true}catch(e){try{const t=document.createElement("textarea");t.value=String(v);t.setAttribute("readonly","");Object.assign(t.style,{position:"fixed",opacity:"0",left:"-9999px"});document.body.appendChild(t);t.select();const ok=document.execCommand("copy");t.remove();if(!ok)throw e;new Notice("Celda copiada");return true}catch(_){new Notice("Pointix: no pude copiar");return false}}}
 async _getSelectedCellPosition(force=false){if(force)this._cachedApi=null;const api=this._cachedApi||this._findUniverApi();if(api)this._cachedApi=api;return this._positionFromApi(api)||this._positionFromDom()}
 _positionFromApi(api){if(!api)return null;try{const wb=api.getActiveWorkbook?.()||api.getCurrentWorkbook?.()||api.getActiveUnit?.(),ws=wb?.getActiveSheet?.()||wb?.getActiveWorksheet?.()||api.getActiveSheet?.(),r=wb?.getActiveRange?.()||ws?.getActiveRange?.()||ws?.getActiveSelection?.()?.getActiveRange?.();if(!ws||!r)return null;const row=this._num(r,["getRow","getStartRow","getRowIndex","startRow","row"]),col=this._num(r,["getColumn","getStartColumn","getColumnIndex","startColumn","column"]);if(row===null||col===null)return null;let sheetId="",sheetName="";try{sheetId=String(ws.getSheetId?.()??ws.getId?.()??"")}catch(_){}try{sheetName=String(ws.getName?.()??ws.getSheetName?.()??"")}catch(_){}return{row,col,sheetId,sheetName}}catch(_){return null}}
 _num(o,ks){for(const k of ks)try{let v=o[k];if(typeof v==="function")v=v.call(o);if(Number.isFinite(Number(v)))return Number(v)}catch(_){}return null}
 _findUniverApi(){const roots=[];for(const[id,p]of Object.entries(this.app?.plugins?.plugins||{})){const s=String(id).toLowerCase();if(s.includes("sheet")||s.includes("excel")||s.includes("univer"))roots.push(p)}const looks=x=>{try{return!!x&&(typeof x.getActiveWorkbook==="function"||(typeof x.getActiveUnit==="function"&&typeof x.executeCommand==="function"))}catch(_){return false}};for(const r of roots)if(looks(r))return r;const q=roots.map(v=>({v,d:0})),seen=new Set();let n=0;while(q.length&&n<18000){const{v,d}=q.shift();if(!v||(typeof v!=="object"&&typeof v!=="function")||seen.has(v))continue;seen.add(v);n++;if(looks(v))return v;if(d>=9)continue;let ns;try{ns=Object.getOwnPropertyNames(v)}catch(_){continue}for(const k of ns){if(["app","parent","containerEl","ownerDocument","window","document"].includes(k))continue;let c;try{const z=Object.getOwnPropertyDescriptor(v,k);if(z?.get&&!("value"in z))continue;c=v[k]}catch(_){continue}if(c&&(typeof c==="object"||typeof c==="function"))q.push({v:c,d:d+1})}}return null}
 _positionFromDom(){for(const e of document.querySelectorAll('[class*="univer"] input,[class*="univer"] textarea,[class*="univer"] [contenteditable="true"],[class*="univer"] [aria-label]')){let s="";try{s=String(e.value??e.textContent??e.getAttribute?.("aria-label")??"").trim()}catch(_){}const m=s.match(/^\$?([A-Z]{1,3})\$?(\d+)(?::\$?[A-Z]{1,3}\$?\d+)?$/i);if(m){let n=0;for(const ch of m[1].toUpperCase())n=n*26+(ch.charCodeAt(0)-64);return{row:Number(m[2])-1,col:n-1,sheetId:"",sheetName:""}}}return null}
};